### PR TITLE
Update Base.php

### LINKED ISSUE #7: custom primary key column name
Needs a way to configure the primary key name, not all of us have systems where `id` is the PK :)

### PR DESCRIPTION
**Pull request by geggleto**
Added ability to set a custom Primary Key column

Fixes #7

### CODE REVIEW

**Comment by geggleto** [comment]
I forgot to update Readme.md with usage...

**Comment by erusev** [comment]
Thanks for this, but I feel that it'd be more consistent w/ the design of the class to implement this as an instance variable, similar to: https://github.com/erusev/base/blob/master/src/Base.php#L236

**Comment by geggleto** [comment]
Public variables are in general a no-no from a design point of view.

While I realize it's more convenient. I plan on using this package in production and I need proper object oriented design.

**Comment by erusev** [comment]
Sure, but for this specific class I'm unable to see the practical benefits of the more complicated approach : (

**Comment by geggleto** [comment]
Well I'll just use my own repo then, np.

**Comment by erusev** [comment]
Can u see actual practical benefits? I'd like to know.

**Comment by geggleto** [comment]
@erusev 

1) Using getter's and setters allow you the chance to validate the inputs and outputs.
2) Using getter's and setters allow you to "Watch" the value which is very useful for debugging
3) Finally you can force a type on a member variable. With a public variable you can set it to literally anything you want, which is terrible practice and leads to security problems.

Finally hiding it follows basic Object oriented design [ Encapsulation ]. In encapsulation a class is responsible to all variables that are contained inside this class.

While in this particular scenario, all of this might seem rather trivial, however when developing open source software is very common to try and prevent the end-user from doing things they should or should not.

**Comment by erusev** [comment]
Thanks @geggleto, this is an excellent explanation and excellent points but, as you seem to agree, these excellent points while true in general might not make much sense in the context of this particular case. I use getters and setters extensively, but I think that the design of this particular library is simple enough to allow for the more minimalistic approach of the public instance variables. I'd reconsider if I see practical issues w/ the current approach, but until then I feel like the simplicity of the public instance variables is too great to dismiss in favor of the arguable, in this particular case, value of the more complicated approach. I hope that this makes sense.

**Pull request closed without merging**
